# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.machada.io" # the base hostname & protocol for your site
imageurl: "img/header/header.jpg" #"https://unsplash.it/2600/500?random"https://source.unsplash.com/category/nature/2600x500

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: MACHA DA COSTA
  #avatar: img/machada.png
  hometitle:  #display on navigation menu.
  yoursitetitle: 
  gravatar: # Email MD5 hash
  description: "This blog is about Android, Android Wear, Mobile Tech and chill out. By Macha Da Costa" # used by search engines
  visiblewords: 50
  # Header and footer text
  header_text: "BORN TO BE MOBILE !"

  header_text_feature_image: 
  place_holder_image:
  footer_text: >
   <a href="https://www.machada.io">MACHA DA</a> 

  # Icons
  rss: false
  email_address: "macha@chillcoding.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "machada.fr"
  flickr:
  github: "machadaCosta"
  weibo: 
  google_plus:
  instagram:
  linkedin:  "http://fr.linkedin.com/in/machadacosta"
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "machaDaCosta"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-55688141-6
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: "fengzhichu.com"
paginate: 4
paginate_path: "/blog/page:num"
permalink: /blog/  #Delete preurl 'fengzhichu-theme/' if used for your personal site.

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS

  
# highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from


